VECTOR			Do		Test

constructor		[ ]		[ ]
operator=		[ ]		[ ]
assign			[ ]		[ ]
get_allocator	[x]		[ ]
at				[x]		[ ]
operator[]		[x]		[ ]
front			[x]		[ ]
back			[x]		[ ]
begin			[x]		[ ]
end				[x]		[ ]
rebgin			[x]		[ ]
rend			[x]		[ ]
empty			[x]		[ ]
size			[x]		[ ]
max_size		[x]		[ ]
reserve			[ ]		[ ]
capacity		[x]		[ ]
clear			[ ]		[ ]
insert			[ ]		[ ]
erase			[ ]		[ ]
push_back		[x]		[ ]
pop_back		[ ]		[ ]
resize			[ ]		[ ]
swap			[ ]		[ ]
// operator==		[ ]		[ ]
