VECTOR			Do		Test

constructor		[x]		[ ]
operator=		[x]		[ ]
assign			[x]		[ ]
get_allocator	[x]		[ ]
at				[x]		[ ]
operator[]		[x]		[ ]
front			[x]		[ ]
back			[x]		[ ]
begin			[x]		[ ]
end				[x]		[ ]
rebgin			[x]		[ ]
rend			[x]		[ ]
empty			[x]		[ ]
size			[x]		[ ]
max_size		[x]		[ ]
reserve			[x]		[ ]
capacity		[x]		[ ]
clear			[x]		[ ]
insert			[x]		[ ]
erase			[x]		[ ]
push_back		[x]		[ ]
pop_back		[x]		[ ]
resize			[x]		[ ]
swap			[x]		[ ]
//operator==		[ ]		[ ]

================================================================================

MAP				Do		Test

destructor		[x]		[ ]
constructor		[x]		[ ]
operator=		[ ]		[ ]
begin			[x]		[ ] //ATTENTION REALLY NEED TO DO THE CONST VERSION
end				[x]		[ ]
rebgin			[x]		[ ]
rend			[x]		[ ]
empty			[x]		[ ]
size			[x]		[ ]
max_size		[x]		[ ]
operator[]		[ ]		[ ]
insert			[ ]		[ ]
erase			[ ]		[ ]
swap			[ ]		[ ]
clear			[x]		[ ]
key_comp		[ ]		[ ]
value_comp		[ ]		[ ]
find			[ ]		[ ] //ne marche vraiment pas
count			[x]		[ ]
lower_bound		[ ]		[ ]
upper_bound		[ ]		[ ]
equal_range		[ ]		[ ]
get_allocator	[ ]		[ ]
iterator		[ ]		[ ]